capfourAssettype_dict = {'Bond_GovernmentBond': 'Government Bond', 'Bond_FixedRateBond': 'Fixed Rate Bond',
                         'Bond_StepFixedRateBond': 'Step Fixed Rate Bond',
                         'Bond_FloatingRateNote': 'Floating Rate Note',
                         'Bond_StepFloatingRateNote': 'Step Floating Rate Note',
                         'Bond_FixedToFloatingRateNote': 'Fixed To Floating Rate Note',
                         'Bond_FixedToVariableRateNote': 'Fixed To Variable Rate Note',
                         'Bond_PayInKindNoteFixed': 'Pay In Kind Note Fixed',
                         'Bond_PayInKindNoteFloat': 'Pay In Kind Note Float',
                         'Bond_PayInKindNoteFixedStep': 'Pay In Kind Note Fixed Step',
                         'Bond_PayInKindNoteFloatStep': 'Pay In Kind Note Float Step',
                         'Bond_ZeroCouponBond': 'Zero Coupon Bond',
                         'Loan_LeveragedLoan': 'Leveraged Loan',
                         'BondLike_FixedRateMortgageBond': 'Fixed Rate Mortgage Bond',
                         'Loan_DirectLoan': 'Direct Loan',
                         'EquityLike_PreferredShares': 'Preferred Equity Shares',
                         'EquityLike_UnlistedEquity': 'Unlisted Equity Shares',
                         'BondLike_FloatingRateMortgageBond': 'Floating Rate Mortgage Bond',
                         'BondLike_AssetBackedSecurity': 'Asset Backed Security',
                         'BondLike_CollateralizedLoanObligation': 'Collateralized Loan Obligation',
                         'CreditDerivative_CreditDefaultSwapSovereign': 'Credit Default Swap Sovereign',
                         'CreditDerivative_CreditDefaultSwapSingleName': 'Credit Default Swap Single Name',
                         'CreditDerivative_CreditDefaultSwapIndex': 'Credit Default Swap Index',
                         'CreditDerivative_LoanCreditDefaultSwap': 'Loan Credit Default Swap',
                         'CreditDerivative_TotalReturnSwap': 'Total Return Swap',
                         'CreditDerivative_CdsIndexOption': 'Credit Default Swap Index Option',
                         'CreditDerivative_CreditDefaultTranche': 'Credit Default Tranche',
                         'Convertible_ConvertibleBond': 'Convertible Bond',
                         'ForeignExchange_ForeignExchangeForward': 'Foreign Exchange Forward',
                         'ForeignExchange_ForeignExchangeOption': 'Foreign Exchange Option', 'Cash_Cash': 'Cash',
                         'Cash_Deposit': 'Cash',
                         'Cash_PayableReceivable': 'Payable/Receivable', 'Cash_Collateral': 'Collateral',
                         'Cash_MoneyMarketFund': 'Money Market Fund',
                         'Other_Claim': 'Claim'
                         }

region_dict = {'Africa': 'Other', 'East Asia & Pacific': 'Other',
               'Europe & Central Asia': 'Other',
               'Latin America & Caribbean': 'North America',
               'Middle East & North Africa': 'Other',
               'Sub-Saharan Africa': 'Other'}

ratingDict_FromNum = {0: ' ', 1: 'AAA', 2: 'AA+', 3: 'AA', 4: 'AA-', 5: 'A+', 6: 'A', 7: 'A-', 8: 'BBB+', 9: 'BBB',
                      10: 'BBB-', 11: 'BB+',
                      12: 'BB', 13: 'BB-', 14: 'B+', 15: 'B', 16: 'B-', 17: 'CCC+', 18: 'CCC', 19: 'CCC-', 20: 'CC',
                      21: 'C', 22: 'D',
                      23: 'NR'}
